config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'my_questions#index'
   resources :blogs do
   	resources :comments
   	# member do
    #     post "create_comment"
   	# end
   end
    post 'comment',:to=> 'comments#rakesh'
    post 'abc/xyz',:to=> 'blogs#create_comment'

    post 'comment',:to=> 'blogs#comment'
     
     get 'question/new', :to=> 'questions#question_new'
     post 'question/create', :to=> 'questions#question_create'
     get 'display/myquestion/:id', :to => 'questions#display_my_question'
     get 'all_question', :to => 'questions#all_question'
     #post 'question/answer', :to => 'answers#answer_create'
     get 'answers/new', :to=> 'answers#answers_new'


     get 'question/:question_id/answer',:to=> 'answers#answers_new'
     post 'question/:question_id/answer',:to=> 'answers#answer_create'
    
     resources :my_questions do
        #post 'question/submit',:to=> 'my_questions#submit'
        resources :question_answers
        
     end
     post 'question/submit_ans',:to=> 'my_questions#submit_ans'
     get 'my_correctanswers', :to => 'my_questions#all_correctans'
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question, optional:true
	belongs_to :submit, optional:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artical.rb
class Artical < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog, optional:true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/models/submit.rb
class Submit < ApplicationRecord
	has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vijay.rb
class Vijay < ApplicationRecord
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def answer_create
		@ques = Question.find(params[:question_id])
        @answer = @ques.answers.create(ans: params[:answer][:ans])
		redirect_to "/display/myquestion/#{@ques.id}"
	end

	def answers_new
         
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def new
  	@blog = Blog.new
  end
  
  def index
      @blogs = Blog.all
  end
  
 def show
     @blog1 = Blog.find(params[:id])
     @comment = Comment.new
 end

  def edit
 	      @blog2 = Blog.find(params[:id])
  end

 	def update
 		@blog2 = Blog.find(params[:id])
 		@blog2.update(title: params[:blog][:title])
 		redirect_to blog_path(@blog2)
 	end
 
 def destroy

 	 @blog2 = Blog.find(params[:id])
 	 @blog2.destroy
 	 redirect_to blogs_path
 end

  def create
  	     @blog = Blog.create(title: params[:blog][:title])

  	     redirect_to blog_path(@blog)

  end

  def create_comment
     @blog = Blog.find(params[:id])
     @blog.comments.create(content: params[:comment][:content])
     redirect_to blog_path(@blog)
  	 
  end
   def comment
         @blog = Blog.find(params[:id])
         @blog.comments.create(content: params[:comment][:content])
         render nothing: true
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
			@blog = Blog.find(params[:blog_id])
			@blog.comments.create(comment_params)
			redirect_to blog_path(@blog)
	end

	def edit
		    @blog1 = Blog.find(params[:blog_id])
		    @comment = @blog1.comments.find(params[:id])	
	end

	def update
	         @blog1 = Blog.find(params[:blog_id])
	         @g = @blog1.comments.find(params[:id])
	         @g.update(content: params[:comment][:content])
	         redirect_to blog_path(@blog1)
	end

	# def rakesh
	# 	@blog = Blog.find(params[:id])
    #         @blog.comments.create(comment_params)
   

	# 	render nothing: true
	# end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

end

app/controllers/my_questions_controller.rb
class MyQuestionsController < ApplicationController
    before_action :set_my_question, only: [:show, :update, :edit]
    before_action :authenticate_user!

		def new
			@my_question = Question.new
		end

		def create

			if current_user.admin == true  
				@question = Question.create(question_params)
				redirect_to my_question_path(@question),notice: 'Question was successfully created.'
			
		    end

		end

		def index
			@questions = Question.all
		end

		def show
			
		end

		 def edit
         
		 end

		 def update
		 	if current_user.admin == true
		 	    @question.update(question_params)
	            redirect_to my_question_path(@question),notice: 'Question was successfully Updated.'
	        end
		 end

		 def submit_ans
		 	 @ans = Answer.all
		 	  @ans.each do |ans|
		 	  	if  ans.id == params[ans.id.to_s].to_i
		 	  		Submit.create(answer_id: params[ans.id.to_s].to_i ,disabled: true ,user_id: current_user.id)
		 	  	end
		 	  end
		 	 redirect_to my_correctanswers_path
		 end


          def all_correctans

          	#@ans = Answer.all
          	@questions = Question.all
          	@submits = Submit.all.where(user_id: current_user.id ,disabled: true)

          end

		 private
		 
	      def set_my_question
	      	   @question = Question.find(params[:id])
	      end

	      def question_params
	      	params.require(:question).permit(:name)
	      end 

end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController
   before_action :authenticate_user!
	def new
		@question = Question.find(params[:my_question_id])
	end

	def create
	 if current_user.admin == true 
		@ques = Question.find(params[:my_question_id])
        @answer = @ques.answers.create(answer_params)
	    redirect_to my_question_path(id: @ques),notice: 'answer was successfully created.'
      end   
	end

	def edit
	    if current_user.admin == true
		 @question = Question.find(params[:my_question_id])
         @answer = @question.answers.find(params[:id])
       end
	end

	def update

	    if current_user.admin == true
		  @question = Question.find(params[:my_question_id])
		  @ans = @question.answers.find(params[:id])
		  @ans.update(answer_params)
		  redirect_to my_question_path(id:@question),notice: 'answer was successfully update.'
	   end
	end

	private

	def answer_params
		params.require(:answer).permit(:ans,:disabled,:question_id,:option)
	end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def question_new
		
	end
    
    def question_create
    	 @question = Question.create(name: params[:question][:name])
    	 redirect_to all_question_path
    end

    def display_my_question
        @question = Question.find(params[:id])

    end
    
    def all_question
    	@questions = Question.all
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/my_questions_helper.rb
module MyQuestionsHelper
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/answers_new.html.erb
<%= form_for :answer, url: {controller: "answers" ,action: "answer_create" } do |form| %>
 <%= form.label :answer %>
 <%= form.text_field :ans %>
 <%= form.submit %>

<%end%>

app/views/blogs/_comment_form.html.erb
<%= form_for ([@blog1, @comment ]) do |form| %>
<%#= form_for :comment, url: {controller: "blogs" ,action: "comment", params: {id: @blog1.id}} do |form| %>
  <%= form.label :content %>
 <%= form.text_field :content %>
 <%= form.submit %>
<%end%>

app/views/blogs/destroy.html.erb
dssdfds

app/views/blogs/edit.html.erb
<%= form_for (@blog2) do |form| %>

 <%= form.label :title %>
 <%= form.text_field :title %>
 <%= form.submit %>

<%end%>

app/views/blogs/index.html.erb
<% @blogs.each do |blog|%>
 <p>
 <%= blog.id %>
 <%= blog.title %>
 <%= link_to 'edit', edit_blog_path(blog)%>
 <%= link_to 'delete', blog_path(blog),method: :delete %>
 </p>
<%end%>

app/views/blogs/new.html.erb
<%= form_for (@blog) do |form| %>

 <%= form.label :title %>
 <%= form.text_field :title %>
 <%= form.submit %>

<%end%>

app/views/blogs/show.html.erb
<%= @blog1.title %>
<%= link_to 'show_all blogs', blogs_path%>

<% @blog1.comments.each do |com| %>
<p>
  comment
  <%= com.content%>
  <%= link_to 'edit_comment', edit_blog_comment_path(@blog1,com)%>
  </p>
<% end%>
<%= render 'comment_form' %>

app/views/comments/edit.html.erb
<%= render 'blogs/comment_form' %>

app/views/my_questions/_form.html.erb
<%#= form_for :question do |form| %>
<%= form_for :question,url:"/my_questions" do |form|%>
 <%= form.label :question %>
 <%= form.text_field :name %>
 <%= form.submit %>

<%end%>

app/views/my_questions/all_correctans.html.erb
<% @questions.each do |question| %>
   <h4>Question:-</h4><%= question.name %>
     <% question.answers.each do |answer| %>
	     <% @submits.each do |s| %>
		       <% if answer.option == s.disabled && answer.id == s.answer_id %>
                     
		            <strong>Answer:-</strong> <%= answer.ans %>
                 
		       <%end%>
	     <%end%>
   <%end%>
<%end%>

app/views/my_questions/edit.html.erb
<%= form_for :question,url:"/my_questions/#{@question.id}",method: :PATCH do |form|%>
 <%= form.label :question %>
 <%= form.text_field :name %>
 <%= form.submit %>

<%end%>

app/views/my_questions/index.html.erb
<%= form_for :submit ,url:"/question/submit_ans", method: :POST do |f|%>
<% @questions.each do |question| %>
<p>
   <strong>Question:-</strong><%= question.name %>
   <%#= f.hidden_field :question_id, :value => question.id %>
   <% question.answers.each do |answer| %>
      <p>
       <strong>Answer:-</strong> <%= answer.ans %>
       <input type="checkbox" name="<%= answer.id %>" value="<%= answer.id %>" > <br> </p>
    
   <%end%>
</p>

<%end%>

   <% unless Submit.where(user_id: current_user.id).first.present? %>
       <%= f.submit "submit"%>
       <%else%>
        <p> You alredy submit a form </p>
   <%end%>
<%end%>

app/views/my_questions/new.html.erb
<% if current_user.admin == true%>
<%= render 'form' %>
<% end %>

app/views/my_questions/show.html.erb
<% if current_user.admin == true %>
	<p>
	<h4> Question </h4><%= @question.name %> 
	<%= link_to 'Edit_Question',edit_my_question_path(@question) %>||
	<%= link_to 'Create Question',new_my_question_path %>
	</p>
	<%= link_to 'All question', my_questions_path %>

	<% @question.answers.each do |answer| %>
	 <p>
	   <h4> Answer</h4><%= answer.ans%>
	   <%= link_to 'Answer edit', edit_my_question_question_answer_path(@question,answer.id) %>
	</p>
	<%end%>

	<%= link_to 'Add Answer', new_my_question_question_answer_path(@question) %>
	<% else %>
	  <p> you have not access </p>
<% end %>

app/views/question_answers/edit.html.erb
<%= form_for :answer,url:"/my_questions/#{@question.id}/question_answers/#{@answer.id}", method: :PATCH do |form|%>
<%= form.text_field :ans %>
<%= form.submit %>
<%end%>

app/views/question_answers/new.html.erb
<%= form_for :answer,url:"/my_questions/#{@question.id}/question_answers" do |form|%>
 <%= form.label :answer %>
 <%= form.text_field :ans %>
 <!-- <select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select> -->
<%= form.label :ans_option %>
<%#= select_tag "option", "<option>a</option><option>b</option><option>c</option><option>d</option>".html_safe%>
 <%= form.check_box :option, {}, true, false %>
 <%= form.submit %>

<%end%>

app/views/questions/all_question.html.erb
<% @questions.each do |ques| %>

 <p>
    <strong >Question</strong> :- <%= ques.name %>
   </p>
  <% ques.answers.each do |an| %>
  <p>
   <strong >Answer</strong> :- <%= an.ans %>
 </p>
  <% end %>
<%end%>

app/views/questions/display_my_question.html.erb
<%= @question.name%>

<% @question.answers.each do |a| %>
<%= a.ans %>
<% end %>

<%= form_for :answer,url:"/question/#{@question.id}/answer" do |form|%>

<%= form.text_field :ans %>
<%= form.submit %>
<%end%>

app/views/questions/question_new.html.erb
<%#= form_for (@question) do |form| %>
<%= form_for :question, url: {controller: "questions" ,action: "question_create"} do |form| %>
 <%= form.label :question %>
 <%= form.text_field :name %>
 <%= form.submit %>

<%end%>